# ----
# Site

title: Navalia API
url: "https://long-pig.cloudvent.net"
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Simple, easy-to-use browser automation at scale.
author:
  name: Joel Griffith
  email: navalia@joelgriffith.net
  twitter: griffith_joel
social:
  name: Edition Template
  links:
    - https://github.com/CloudCannon/edition-jekyll-template

# -----
# Build

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
